# Generated by Django 3.0 on 2019-12-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20191212_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
